MorphicWin/App.xaml.cs
MorphicWin/MorphicWin.csproj
MorphicWin/QuickStrip.xaml.cs
MorphicWin/appsettings.json
azure-pipelines.yml

first pass at adding countly events

---

MorphicCore.Tests/PreferencesTests.cs
MorphicCore/Preferences.cs
MorphicService/PreferencesService.cs
MorphicService/Session.cs
MorphicService/UserService.cs
MorphicSettings.Tests/RegistrySettingsHandlerTests.cs
MorphicSettings/ApplySession.cs
MorphicSettings/CaptureSession.cs
MorphicSettings/Ini/IniFile.cs
MorphicSettings/Ini/IniSettingHander.cs
MorphicSettings/Registry/RegistrySettingHandler.cs
MorphicSettings/Registry/WindowsRegistry.cs
MorphicSettings/Setting.cs
MorphicSettings/SettingHandler.cs
MorphicSettings/Settings.cs
MorphicSettings/SystemSettings/SystemSettingHandler.cs
MorphicWin/Solutions.json
MorphicWin/Travel/CapturePanel.xaml.cs
MorphicWin/Travel/CreateAccountPanel.xaml.cs
MorphicWin/Travel/TravelWindow.xaml.cs

- adjust setting handlers to take setting objects instead of just a descriptions so they can return the expected types
- add a loose type comparison for setting values
- add preference copy constructor
- add preference remove method

get capture working

---

Morphic.Client/About/AboutWindow.xaml
Morphic.Client/About/AboutWindow.xaml.cs
Morphic.Client/Login/LoginWindow.xaml
Morphic.Client/Login/LoginWindow.xaml.cs
Morphic.Client/appsettings.Development.json
Morphic.Client/appsettings.json
Morphic.Service/Session.cs

add links for password reset and contact us

---

Morphic.Client/QuickStrip/QuickStripSegmentedButtonControl.xaml.cs

adjust button styles to avoid two-tone low contrast for everyone

---

Morphic.Client/QuickStrip/QuickStripWindow.xaml.cs
Morphic.Settings/Registry/RegistrySettingHandler.cs
Morphic.Settings/SettingsManager.cs

Changed the magnifier button to configure magnifier to lens mode at 200%, and restore the previous setting when closing.
Closes #74

Starts the magnifier in lens mode at 200%

---

Morphic.Client/QuickStrip/QuickStripWindow.xaml.cs

Stopped the reader crashing due to clipboard problems.

---

Morphic.Client/QuickStrip/QuickStripSegmentedButtonControl.xaml
Morphic.Client/QuickStrip/QuickStripSegmentedButtonControl.xaml.cs

Improved the visibility of the keyboard focus, and made tooltips follow.

MOR-61,MOR-59: Keyboard focus accessibility.

---

Morphic.Client/App.xaml
Morphic.Client/App.xaml.cs

Adds an entry to the registry that starts the process at login. This can be turned off in the tray menu.

MOR-56: Automatically starting Morphic at login.

---

Morphic.Setup/Product.wxs

Updated the installer to add a desktop icon.

MOR-90: Added desktop icon.

---

Morphic.Client/DefaultPreferences.json
Morphic.Client/Properties/Resources.Designer.cs
Morphic.Client/Properties/Resources.resx
Morphic.Client/QuickStrip/QuickStripWindow.xaml.cs
Morphic.Client/Solutions/windows.solutions.json
Morphic.Settings/SettingsManager.cs

Replaces high-contrast with night mode.
(I don't have a native windows machine to see the effect of night mode colouring, but it does change the setting)

MOR-88: Night mode

---

Morphic.Bar/Bar/Actions/Personal.cs
Morphic.Bar/DefaultConfig/presets.json5

Now starting in lens mode, with buttons renamed to `Show` and  `Hide`

Made the magnifier buttons like Morphic quickstrip.

---

Morphic.Client/About/AboutWindow.xaml
Morphic.Client/App.xaml
Morphic.Client/App.xaml.cs
Morphic.Client/AppOptions.cs
Morphic.Client/Backups.cs
Morphic.Client/Elements/StepFrame.cs
Morphic.Client/Login/LoginPanel.xaml
Morphic.Client/Login/LoginPanel.xaml.cs
Morphic.Client/Login/LoginWindow.xaml
Morphic.Client/Login/LoginWindow.xaml.cs
Morphic.Client/Morphic.Client.csproj
Morphic.Client/QuickStrip/QuickHelpWindow.xaml.cs
Morphic.Client/QuickStrip/QuickStripSegmentedButtonControl.xaml.cs
Morphic.Client/QuickStrip/QuickStripWindow.xaml.cs
Morphic.Client/Travel/ApplyPanel.xaml
Morphic.Client/Travel/ApplyPanel.xaml.cs
Morphic.Client/Travel/CopyStartPanel.xaml
Morphic.Client/Travel/CopyStartPanel.xaml.cs
Morphic.Client/Travel/CreateAccountPanel.xaml
Morphic.Client/Travel/CreateAccountPanel.xaml.cs
Morphic.Client/Travel/RestoreWindow.xaml
Morphic.Client/Travel/RestoreWindow.xaml.cs
Morphic.Client/Travel/TravelWindow.xaml
Morphic.Client/Travel/TravelWindow.xaml.cs
Morphic.Settings/Display.cs
Morphic.Windows.Native/Speech/SelectionReader.cs

Various things from the 1.0 checklist

More for mvp 1.1

---

Morphic.Client/App.xaml.cs
README.md
azure-pipelines.yml

Also removed the build tag (from the old MorphicLite CI/CD)

Update 'MorphicLite' to 'Morphic'

---

Morphic.Client/Dialogs/Travel/CopyStartPanel.xaml

Test button, should not have been commited.

MOR-362: Removed test button.

---

Morphic.Client/Bar/BarData.md
Morphic.Client/Bar/Data/BarJson.cs
Morphic.Client/Bar/Data/BarPosition.cs
Morphic.Client/Bar/UI/BarWindow.xaml.cs
Morphic.Client/Bar/UI/PrimaryBarWindow.cs
Morphic.Client/DefaultConfig/basic-bar.json5

Added options for:
- Disable docking.
- Limit positioning to the corners.

MOR-363: Options to limit bar positions

---

Morphic.Client/Bar/BarData.md
Morphic.Client/Bar/Data/BarItemTheme.cs
Morphic.Client/Bar/UI/BarControls/ButtonBarControl.xaml
Morphic.Client/Bar/UI/BarControls/ImageBarControl.xaml
Morphic.Client/Bar/UI/BarControls/MultiButtonBarControl.xaml
Morphic.Client/Bar/UI/BarControls/MultiButtonBarControl.xaml.cs
Morphic.Client/DefaultConfig/basic-bar.json5
Morphic.Client/DefaultConfig/default-bar.json5

Replaces https://github.com/raisingthefloor/morphic-windows/pull/131

MOR-335: Made keyboard navigation focus rects work.

---

azure-pipelines.yml

Uncomment the code that updates the URL in the Azure pipeline. Also updates the Cloudfront endpoint and the pipeline git resource for deploy-morphicweb.

Update azure-pipeline to change the download url

---

Morphic.Client/Config/AppOptions.cs

Checklist item 29
Fixed startup error `String '1' was not recognized as a valid Boolean`

MOR-308.29: Fixed startup error

---

Morphic.Client/solutions.json5
Morphic.Core/TypeConversion.cs
Morphic.Settings/SettingsHandlers/Registry/RegistrySettingsHandler.cs
Morphic.Settings/SettingsHandlers/Setting.cs

Settings where being written to the registry as a different data type.

Made settings respect their data type

---

Morphic.Client/App.xaml.cs
Morphic.Client/Bar/BarImages.cs
Morphic.Client/Bar/Data/BarButton.cs
Morphic.Client/Bar/Data/BarData.cs
Morphic.Client/Bar/Data/BarItem.cs
Morphic.Client/Bar/UI/BarControls/ButtonBarControl.xaml.cs
Morphic.Client/Bar/UI/BarWindow.xaml.cs
Morphic.Client/Bar/UI/Converters.cs
Morphic.Client/DefaultConfig/default-bar.json5
Morphic.Client/Dialogs/CommunityLoginWindow.xaml
Morphic.Client/Menu/MorphicMenu.xaml
Morphic.Client/Menu/MorphicMenu.xaml.cs
Morphic.Client/Properties/launchSettings.json
Morphic.Client/appsettings.Debug.json
Morphic.Client/appsettings.Production.json
Morphic.Service/CommunitySession.cs
Morphic.Service/HttpService.cs
Morphic.Service/MorphicSession.cs
Morphic.Service/Session.cs
README.md

Getting morphic community to work, after the code merge and front-end updates.

community release

---

Morphic.Client/Bar/Data/Actions/ApplicationAction.cs
Morphic.Client/Morphic.Client.csproj
Morphic.Client/test-bar.json5
Morphic.Windows.Native/WindowsCom/Appx.cs

Added support for applications in the web-app.

MOR-123: Starting store apps.

---

Morphic.Client/Dialogs/Travel/CreateAccountPanel.xaml.cs

Morphic v1.2 Preview 4
